version: '3.1'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: pa55w0rd!
      MSSQL_PID: Express
    ports:
      - 1433:1433
    volumes:
      - /home/admroot/graphQLDockerSql/CommanderGQL/sqlserver-data:/var/opt/mssql